### ISSUE TITLE
Create and run a new project

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/post-master#1]
# Tasks

- [ ] Create and run a new project

```
git clone https://github.com/sinProject-Inc/post-master.git
npm create svelte@latest post-master
cd post-master
npm i
npm run dev -- --open
```

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
